//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Enteries
    {
        public int EntryID { get; set; }
        public int ProjectID { get; set; }
        public string StartDate { get; set; }
        public string StartTime { get; set; }
        public string EndDate { get; set; }
        public string EndTime { get; set; }
    
        public virtual TT_Projects TT_Projects { get; set; }
    }
}
